const en = {
  app_name: 'Enatega Deliveries Store App',
  welcome_title: 'Store Partner Workspace',
  welcome_subtitle: 'Theme, localization, and reusable base components are ready.',
  change_theme: 'Switch theme',
  change_language: 'Switch language',
  current_theme: 'Theme mode: {{mode}}',
  current_language: 'Language: {{language}}',
  // Auth
  auth_title: 'Enter Your Credentials to login',
  auth_subtitle: "We'll check if you have an account",
  auth_email_placeholder: 'Email',
  auth_password_placeholder: 'Password',
  auth_login: 'Login',
  auth_login_loading: 'Logging in...',
  auth_logout: 'Log Out',
  auth_logout_loading: 'Logging out...',
  auth_email_required: 'Email is required',
  auth_email_invalid: 'Enter a valid email address',
  auth_password_required: 'Password is required',
  // Bottom nav
  nav_home: 'Home',
  nav_wallet: 'Wallet',
  nav_earnings: 'Earnings',
  nav_profile: 'Profile',
  // Home / Orders
  orders_title: 'Orders',
  orders_tab_new: 'New Order',
  orders_tab_processing: 'Processing',
  orders_tab_delivered: 'Delivered',
  // Profile
  profile_title: 'Profile',
  profile_bank_details: 'Bank details',
  profile_updated: 'Updated',
  profile_vehicle_plate: 'Vehicle Plate',
  profile_address: 'Address',
  profile_phone: 'Phone No',
  profile_username: 'Username',
  profile_wallet_balance: 'Wallet Balance',
  profile_theme: 'Theme',
  profile_availability: 'Availability',
  // Language
  language_title: 'Language',
  language_update: 'Update Language',

  // Orders / NewOrdersScreen
  orders_tab_delivery: 'Delivery Orders',
  orders_tab_pickup: 'Pickup Orders',
  orders_no_more: 'No more orders',
  orders_empty_delivery: 'No delivery orders',
  orders_empty_pickup: 'No pickup orders',

  // OrderCard
  order_card_id_label: 'Order ID:',
  order_card_col_order: 'ORDER',
  order_card_col_price: 'PRICE',
  order_card_total: 'Total',
  order_card_comment: 'Comment',
  order_card_type_delivery: 'Delivery',
  order_card_type_pickup: 'Pickup',
  order_card_reject: 'Reject',
  order_card_accept: 'Accept',
  order_card_delivered: 'Delivered',
  order_card_rider_arrived: 'Rider arrived',
  order_card_preparing: 'Preparing',
  order_card_mark_ready: 'Mark as Ready',
  order_card_heading_customer: 'Heading to Customer',
  order_card_confirm_pickup: 'Confirm Pickup',
  order_card_rider_name: 'Rider Name',
  order_card_payment_method: 'Payment method',
  order_card_date_time: 'Date & Time',
  order_card_payment_cod: 'COD',
  minutes_abbr: 'min',
  no_orders_here: 'No orders here yet',
  set_preparing_time: 'Set preparing time',
  done: 'Done',
};

export default en;