const fr = {
  app_name: "Enatega Deliveries Store App",
  welcome_title: "Espace partenaire magasin",
  welcome_subtitle:
    "Theme, localisation et composants de base reutilisables sont prets.",
  change_theme: "Changer le thème",
  change_language: "Changer la langue",
  current_theme: "Mode de thème: {{mode}}",
  current_language: "Langue: {{language}}",
  // Auth
  auth_title: "Entrez vos identifiants pour vous connecter",
  auth_subtitle: "Nous vérifierons si vous avez un compte",
  auth_email_placeholder: "E-mail",
  auth_password_placeholder: "Mot de passe",
  auth_login: "Se connecter",
  auth_login_loading: "Connexion...",
  auth_logout: "Se deconnecter",
  auth_logout_loading: "Deconnexion...",
  auth_email_required: "L'e-mail est requis",
  auth_email_invalid: "Entrez une adresse e-mail valide",
  auth_password_required: "Le mot de passe est requis",
  // Bottom nav
  nav_home: "Accueil",
  nav_wallet: "Portefeuille",
  nav_earnings: "Revenus",
  nav_profile: "Profil",
  // Home / Orders
  orders_title: "Commandes",
  orders_tab_new: "Nouvelle",
  orders_tab_processing: "En cours",
  orders_tab_delivered: "Livrée",
  // Profile
  profile_title: "Profil",
  profile_bank_details: "Coordonnées bancaires",
  profile_updated: "Mis à jour",
  profile_vehicle_plate: "Plaque du véhicule",
  profile_address: "Adresse",
  profile_phone: "Téléphone",
  profile_username: "Nom d'utilisateur",
  profile_wallet_balance: "Solde du portefeuille",
  profile_theme: "Thème",
  profile_availability: "Disponibilité",
  // Language
  language_title: "Langue",
  language_update: "Mettre à jour la langue",

  // Orders / NewOrdersScreen
  orders_tab_delivery: "Commandes livraison",
  orders_tab_pickup: "Commandes à emporter",
  orders_no_more: "Plus de commandes",
  orders_empty_delivery: "Aucune commande de livraison",
  orders_empty_pickup: "Aucune commande à emporter",

  // OrderCard
  order_card_id_label: "ID commande :",
  order_card_col_order: "COMMANDE",
  order_card_col_price: "PRIX",
  order_card_total: "Total",
  order_card_comment: "Commentaire",
  order_card_type_delivery: "Livraison",
  order_card_type_pickup: "À emporter",
  order_card_reject: "Refuser",
  order_card_accept: "Accepter",
  order_card_delivered: "Livrée",
  order_card_rider_arrived: "Livreur arrivé",
  order_card_preparing: "En préparation",
  order_card_mark_ready: "Marquer comme prêt",
  order_card_heading_customer: "En route vers le client",
  order_card_confirm_pickup: "Confirmer le ramassage",
  order_card_rider_name: "Nom du livreur",
  order_card_payment_method: "Méthode de paiement",
  order_card_date_time: "Date et heure",
  order_card_payment_cod: "Paiement à la livraison",
  minutes_abbr: "min",
  no_orders_here: "Aucune commande ici pour le moment",
  set_preparing_time: "Définir le temps de préparation",
  done: "Terminé",
};

export default fr;