const fr = {
  app_name: 'Enatega Deliveries Store App',
  welcome_title: 'Espace partenaire magasin',
  welcome_subtitle: 'Theme, localisation et composants de base reutilisables sont prets.',
  change_theme: 'Changer le thème',
  change_language: 'Changer la langue',
  current_theme: 'Mode de thème: {{mode}}',
  current_language: 'Langue: {{language}}',
  // Auth
  auth_title: 'Entrez vos identifiants pour vous connecter',
  auth_subtitle: 'Nous vérifierons si vous avez un compte',
  auth_email_placeholder: 'E-mail',
  auth_password_placeholder: 'Mot de passe',
  auth_login: 'Se connecter',
  auth_login_loading: 'Connexion...',
  auth_logout: 'Se deconnecter',
  auth_logout_loading: 'Deconnexion...',
  auth_email_required: "L'e-mail est requis",
  auth_email_invalid: 'Entrez une adresse e-mail valide',
  auth_password_required: 'Le mot de passe est requis',
  // Bottom nav
  nav_home: 'Accueil',
  nav_wallet: 'Portefeuille',
  nav_earnings: 'Revenus',
  nav_profile: 'Profil',
  // Home / Orders
  orders_title: 'Commandes',
  orders_tab_new: 'Nouvelle',
  orders_tab_processing: 'En cours',
  orders_tab_delivered: 'Livrée',
  // Profile
  profile_title: 'Profil',
  profile_bank_details: 'Coordonnées bancaires',
  profile_updated: 'Mis à jour',
  profile_vehicle_plate: 'Plaque du véhicule',
  profile_address: 'Adresse',
  profile_phone: 'Téléphone',
  profile_username: "Nom d'utilisateur",
  profile_wallet_balance: 'Solde du portefeuille',
  profile_theme: 'Thème',
  profile_availability: 'Disponibilité',
  // Language
  language_title: 'Langue',
  language_update: 'Mettre à jour la langue',
  // Bank Management
  bank_title: 'Gestion bancaire',
  bank_currency: 'Devise',
  bank_holder_label: 'Nom complet du titulaire du compte bancaire',
  bank_holder_placeholder: 'ex. Gabriel Gutkowski',
  bank_holder_required: 'Le nom du titulaire est requis',
  bank_iban_label: 'IBAN / Swift / BSB',
  bank_iban_placeholder: 'ex. IT25M0680218128171X4075J102',
  bank_iban_required: 'IBAN / Swift / BSB est requis',
  bank_account_label: 'Numéro de compte',
  bank_account_placeholder: 'ex. 3254465164614411',
  bank_account_required: 'Le numéro de compte est requis',
  bank_confirm: 'Confirmer',
};

export default fr;
