const fr = {
  app_name: "Enatega Deliveries Store App",
  welcome_title: "Espace partenaire magasin",
  welcome_subtitle:
    "Theme, localisation et composants de base reutilisables sont prets.",
  change_theme: "Changer le thème",
  change_language: "Changer la langue",
  current_theme: "Mode de thème: {{mode}}",
  current_language: "Langue: {{language}}",
  // Auth
  auth_title: "Entrez vos identifiants pour vous connecter",
  auth_subtitle: "Nous vérifierons si vous avez un compte",
  auth_email_placeholder: "E-mail",
  auth_password_placeholder: "Mot de passe",
  auth_login: "Se connecter",
  auth_login_loading: "Connexion...",
  auth_logout: "Se deconnecter",
  auth_logout_loading: "Deconnexion...",
  auth_email_required: "L'e-mail est requis",
  auth_email_invalid: "Entrez une adresse e-mail valide",
  auth_password_required: "Le mot de passe est requis",
  // Bottom nav
  nav_home: "Accueil",
  nav_wallet: "Portefeuille",
  nav_earnings: "Revenus",
  nav_profile: "Profil",
  // Home / Orders
  orders_title: "Commandes",
  orders_tab_new: "Nouvelle",
  orders_tab_processing: "En cours",
  orders_tab_delivered: "Livrée",
  // Profile
  profile_title: "Profil",
  profile_bank_details: "Coordonnées bancaires",
  profile_updated: "Mis à jour",
  profile_vehicle_plate: "Plaque du véhicule",
  profile_address: "Adresse",
  profile_phone: "Téléphone",
  profile_username: "Nom d'utilisateur",
  profile_wallet_balance: "Solde du portefeuille",
  profile_theme: "Thème",
  profile_availability: "Disponibilité",
  // Language
  language_title: "Langue",
  language_update: "Mettre à jour la langue",

  // Orders / NewOrdersScreen
  orders_tab_delivery: "Commandes livraison",
  orders_tab_pickup: "Commandes à emporter",
  orders_no_more: "Plus de commandes",
  orders_empty_delivery: "Aucune commande de livraison",
  orders_empty_pickup: "Aucune commande à emporter",

  // OrderCard
  order_card_id_label: "ID commande :",
  order_card_col_order: "COMMANDE",
  order_card_col_price: "PRIX",
  order_card_total: "Total",
  order_card_comment: "Commentaire",
  order_card_type_delivery: "Livraison",
  order_card_type_pickup: "À emporter",
  order_card_reject: "Refuser",
  order_card_accept: "Accepter",
  order_card_delivered: "Livrée",
  order_card_rider_arrived: "Livreur arrivé",
  order_card_preparing: "En préparation",
  order_card_mark_ready: "Marquer comme prêt",
  order_card_heading_customer: "En route vers le client",
  order_card_confirm_pickup: "Confirmer le ramassage",
  order_card_rider_name: "Nom du livreur",
  order_card_payment_method: "Méthode de paiement",
  order_card_date_time: "Date et heure",
  order_card_payment_cod: "Paiement à la livraison",
  minutes_abbr: "min",
  no_orders_here: "Aucune commande ici pour le moment",
  set_preparing_time: "Définir le temps de préparation",
  done: "Terminé",
  // Bank Management
  bank_title: 'Gestion bancaire',
  bank_currency: 'Devise',
  bank_holder_label: 'Nom complet du titulaire du compte bancaire',
  bank_holder_placeholder: 'ex. Gabriel Gutkowski',
  bank_holder_required: 'Le nom du titulaire est requis',
  bank_iban_label: 'IBAN / Swift / BSB',
  bank_iban_placeholder: 'ex. IT25M0680218128171X4075J102',
  bank_iban_required: 'IBAN / Swift / BSB est requis',
  bank_account_label: 'Numéro de compte',
  bank_account_placeholder: 'ex. 3254465164614411',
  bank_account_required: 'Le numéro de compte est requis',
  bank_confirm: 'Confirmer',


  // Wallet
wallet_current_balance: 'Solde actuel',
wallet_available_for_withdrawal: 'Disponible pour retrait :',
wallet_withdraw_now: 'Retirer maintenant',
wallet_available_amount_label: 'Montant disponible',
wallet_enter_amount: 'Entrez le montant',
wallet_confirm_withdraw: 'Confirmer le retrait',
wallet_invalid_amount: 'Veuillez entrer un montant valide',
wallet_pending_request: 'Demande en attente',
wallet_recent_transactions: 'Transactions récentes',
wallet_no_transactions: 'Aucune transaction pour le moment',
wallet_withdrawal_submitted: 'Votre demande de retrait a été soumise',
wallet_withdrawal_eta: 'Cela prend généralement 1 à 2 jours ouvrables',
wallet_withdrawal_failed: 'Échec du retrait',
};

export default fr;